### ISSUE TITLE
Not able to run locally.

### ISSUE THREAD

**Issue by slashgk** [teachaccess/tutorial#32]
Getting a couple of errors when I am trying to run `exerslide serve`. 
<img width="1792" alt="Screenshot 2021-10-16 at 6 37 03 PM" src="https://user-images.githubusercontent.com/19537430/137588801-aa408090-0657-4017-8800-51cf04f525c5.png">

I have run 
`npm install -g exerslide-cli`
`npm install`
`exerslide serve`

**Comment by rachelruderman** [comment]
Interesting, this tutorial hadn't been updated in several years so this must have broken at some point. I'll look into it this week, thank you for creating the issue

**Comment by rachelruderman** [comment]
The `exerslide` framework used by the tutorial has been archived by Facebook for 5 years and is no longer receiving updates. Our options are...
1. Find a way to get this to work with the old exerslide version (I've been trying but it's a toughie)
2. Migrate to a maintained framework (or no framework at all) 

Everyone and anyone is invited to work on this. It's pretty urgent since all other issues depend on local development working

**Comment by rachelruderman** [comment]
To be honest, I'm leaning towards migrating the tutorial to [docusarus](https://docusaurus.io/docs)
